### ISSUE TITLE
make Docker optional 

### ISSUE THREAD

**Issue by cloudnull** [ansible-community/pytest-molecule#13]
In order to use this plugin I need to be able to run scenarios without Docker. Sadly due to the following lines:

* https://github.com/pycontribs/pytest-molecule/blob/c832b13/pytest_molecule/__init__.py#L12-L19

This plugin requires the docker-sdk to be installed and for the docker service to be running.

**Comment by ssbarnea** [comment]
I totally agree that this invalid requirement, the correct way to check for this is to read the molecule.yml file and validate docker presence only if is listed there.

**Comment by ssbarnea** [comment]
This will be sorted via https://github.com/pycontribs/pytest-molecule/issues/20
