### ISSUE TITLE
Make selinux import optional

### ISSUE THREAD

**Issue by cloudnull** [ansible-community/pytest-molecule#14]
To make this library more universal we should remove the selinux requirement or make the requirements check if selinux is present and available before raising an exception on the missing library.

* https://github.com/pycontribs/pytest-molecule/blob/c832b13/pytest_molecule/__init__.py#L21-L34

**Comment by ssbarnea** [comment]
I will limit the check even more by looking for os.path.isfile("/etc/selinux/config") and doing the check only if the file exists.

This should rule out Linux distros which do not have selinux. We care about selinux only on platforms that do have it and is installed.
