### ISSUE TITLE
Molecule is never called ?

### ISSUE THREAD

**Issue by gkoudjou** [ansible-community/pytest-molecule#18]
Hello,

I've just installed this plug-ins and it seems that molecule is never called!

Below is an console extract. I use tox and the expected behavior was to run molecule for each scenario. What happens in place is only running infra test...

> py27-ansible26 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,ansible==2.6.3,ansible-lint==3.4.23,anyconfig==0.9.7,arrow==0.14.2,asn1crypto==0.24.0,atomicwrites==1.3.0,attrs==19.1.0,backports.functools-lru-cache==1.5,backports.ssl-match-hostname==3.7.0.1,bcrypt==3.1.7,binaryornot==0.4.4,Cerberus==1.2,certifi==2019.6.16,cffi==1.12.3,chardet==3.0.4,click==6.7,click-completion==0.3.1,colorama==0.3.9,configparser==3.7.4,contextlib2==0.5.5,cookiecutter==1.6.0,cryptography==2.7,docker==2.7.0,docker-py==1.10.6,docker-pycreds==0.4.0,enum34==1.1.6,fasteners==0.15,flake8==3.5.0,funcsigs==1.0.2,future==0.17.1,git-url-parse==1.2.2,idna==2.8,importlib-metadata==0.18,ipaddress==1.0.22,Jinja2==2.10,jinja2-time==0.2.0,MarkupSafe==1.1.1,mccabe==0.6.1,molecule==2.19.0,molecule-galaxy-wrapper==0.0.4,monotonic==1.5,more-itertools==5.0.0,packaging==19.0,paramiko==2.6.0,pathlib2==2.3.4,pathspec==0.5.9,pbr==4.1.0,pexpect==4.6.0,pluggy==0.12.0,poyo==0.4.2,psutil==5.4.6,ptyprocess==0.6.0,py==1.8.0,pycodestyle==2.3.1,pycparser==2.19,pyflakes==1.6.0,PyNaCl==1.3.0,pyparsing==2.4.0,pytest==4.6.4,pytest-molecule==1.0.1,python-dateutil==2.8.0,python-gilt==1.2.1,PyYAML==3.13,requests==2.22.0,ruamel.ordereddict==0.4.13,ruamel.yaml==0.15.99,scandir==1.10.0,sh==1.12.14,six==1.11.0,tabulate==0.8.2,testinfra==1.16.0,tree-format==0.1.2,urllib3==1.25.3,wcwidth==0.1.7,websocket-client==0.56.0,whichcraft==0.6.0,yamllint==1.11.1,zipp==0.5.2
> py27-ansible26 run-test-pre: PYTHONHASHSEED='559671450'
> py27-ansible26 run-test: commands[0] | pytest
> ===================================================================================== test session starts ======================================================================================
> platform linux2 -- Python 2.7.5, pytest-4.6.4, py-1.8.0, pluggy-0.12.0
> cachedir: .tox/py27-ansible26/.pytest_cache
> rootdir: /home/vagrant/foo_role_test_infra
> plugins: testinfra-1.16.0, molecule-1.0.1
> collected 1 item / 1 errors
> 
> ============================================================================================ ERRORS ============================================================================================
> ___________________________________________________________________ ERROR collecting molecule/default/tests/test_default.py ____________________________________________________________________
> molecule/default/tests/test_default.py:6: in <module>
>     os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')
> .tox/py27-ansible26/lib64/python2.7/UserDict.py:23: in __getitem__
>     raise KeyError(key)
> E   KeyError: 'MOLECULE_INVENTORY_FILE'
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> =================================================================================== 1 error in 1.34 seconds ====================================================================================
> ERROR: InvocationError for command /home/vagrant/foo_role_test_infra/.tox/py27-ansible26/bin/pytest (exited with code 2)
> ___________________________________________________________________________________________ summary ____________________________________________________________________________________________
> ERROR:   py27-ansible26: commands failed
> 

Here is the content tree of my dummy project  

> .
> ├── defaults
> │   └── main.yml
> ├── handlers
> │   └── main.yml
> ├── meta
> │   └── main.yml
> ├── molecule
> │   └── default
> │       ├── Dockerfile.j2
> │       ├── INSTALL.rst
> │       ├── molecule.yml
> │       ├── playbook.yml
> │       └── tests
> │           ├── __pycache__
> │           │   └── test_default.cpython-27-PYTEST.pyc
> │           ├── test_default.py
> │           └── test_default.pyc
> ├── README.md
> ├── tasks
> │   └── main.yml
> ├── tox.ini
> └── vars
>     └── main.yml
> 

Any hint ? Did I misunterstood the actual plugin working ?

Thanks

**Comment by ssbarnea** [comment]
I don't know where that line comes from but is clearly not from here: `os.environ['MOLECULE_INVENTORY_FILE']).get_hosts('all')`
