### ISSUE TITLE
Use Molecule Python API

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible-community/pytest-molecule#4]
Currently we invoke Molecule by opening a shell and executing Molecule as a command. I know there are recommendations from the Ansible developers to not call Ansible via the Python API however I wonder if those concerns also apply to Molecule. I think performance wise it would probably run better if it were natively Python. This would likely need some investigation.

https://github.com/pycontribs/pytest-molecule/blob/9a2a802cccc06869e7764ad77cf5fc07db787c06/pytest_molecule.py#L54

**Comment by ssbarnea** [comment]
I am aware about this but I am not yet convinced there are any tangible benefits of calling it via Python. The speed improvement is negiligble but at the same time we get a better isolation. If something really bad happens with molecule/ansible run, we are likely going to survive it with current approach.

Also, CLI API is less likely to break on newer versions.

**Comment by ssbarnea** [comment]
Do you still find a need for that, or we should close it? I like the idea of avoiding tight-coupling. Obviously that if you make a PR that enables optional calling method (calling __main__ is quite easy), I would not be against it.

**Comment by LukeShortCloud** [comment]
I don't have any requirements for this right now. We can revisit this at a later date if necessary.
