### ISSUE TITLE
survey on default behaviors of pytest molecule

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/pytest-molecule#45]
# Default behavior on discovered delegated scenarios

Running them risks altering the localhost machine, skipping them risks on skipping some tests and not knowing.

It worth noting that the master code displays a warning like below when it it fails to find a specific Ansible variable. 

> Molecule delegated driver was not enabled because missing zuul.build variable in current inventory. We will tag scenarios using it with 'skip' marker.

Obviously that the user can still define `zuul.build` in its molecule.yml with has the side-effect of disabling that safety protection. This was an attempt to distinguish between CI driven executions and non CI ones.

[![](https://api.gh-polls.com/poll/01DQ9XW74H7RVBP0KCC8Q75MPZ/skip%20delegated%20unless%20special%20flag%20is%20added%20to%20pytest)](https://api.gh-polls.com/poll/01DQ9XW74H7RVBP0KCC8Q75MPZ/skip%20delegated%20unless%20special%20flag%20is%20added%20to%20pytest/vote)
[![](https://api.gh-polls.com/poll/01DQ9XW74H7RVBP0KCC8Q75MPZ/run%20delegated%20by%20default)](https://api.gh-polls.com/poll/01DQ9XW74H7RVBP0KCC8Q75MPZ/run%20delegated%20by%20default/vote)
[![](https://api.gh-polls.com/poll/01DQ9XW74H7RVBP0KCC8Q75MPZ/other)](https://api.gh-polls.com/poll/01DQ9XW74H7RVBP0KCC8Q75MPZ/other/vote)

# Default behavior on for scenarios using broken drivers?

Should pytest-molecule decide to skip all tests that cannot be tested because missing or misconfigured drivers? For example if docker is missing it is obvious that docker based scenarios would not be able to run. We can detect that and skip them so a default run of `pytest` would run all tests that are "testable" on current system.

[![](https://api.gh-polls.com/poll/01DQ9X7R0ETZ22G4AEY6BV0SX1/run%20all%20scenarios)](https://api.gh-polls.com/poll/01DQ9X7R0ETZ22G4AEY6BV0SX1/run%20all%20scenarios/vote)
[![](https://api.gh-polls.com/poll/01DQ9X7R0ETZ22G4AEY6BV0SX1/skip%20scenarios%20with%20broken%20drivers)](https://api.gh-polls.com/poll/01DQ9X7R0ETZ22G4AEY6BV0SX1/skip%20scenarios%20with%20broken%20drivers/vote)
[![](https://api.gh-polls.com/poll/01DQ9X7R0ETZ22G4AEY6BV0SX1/other)](https://api.gh-polls.com/poll/01DQ9X7R0ETZ22G4AEY6BV0SX1/other/vote)

If you vote with other, please be sure you add comments below. We are aware that we can expose extra markers of even options for changing behavior but the main issue here is to decide about the default behavior, the one when no arguments are given, as we do not want to change it at any new release.

**Comment by marios** [comment]
"Running them risks altering the localhost machine" sure but i wrote the test so i (should) know this is using delegated driver... why would we skip them. I guess the second option is to add a special flag if we really don't want to run them by default.

**Comment by marios** [comment]
also what changed i mean we were running these yesterday ?

**Comment by ssbarnea** [comment]
@marios The question relates to expectations for new contributors on any repository using pytest-molecule. People are usually confident to run any `tox` command because the tool was designed to perform testing in isolation, without risk of messing your localhost config. While this was never enforceable I can bet that sooner or later we will have someone running `tox` on a role that does some localhost damage just because its author considered easier to test the role on CI, knowing not to run it on his local machine.

**Comment by ssbarnea** [comment]
@cloudnull @ekultails I could use your input, as the decision we make can impact how we use it with openstack related roles.

**Comment by ssbarnea** [comment]
I am closing it but anyone is welcomed to vote on the two questions, especially the 2nd where vote didn't help making a decision.
